name: Syntax Check

on: 
  push:
    branches:
      - main
      - python_oop
      - python_basic
      - python_typing
  pull_request:
   branches:
      - main
      - python_oop
      - python_basic
      - python_typing

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install flake8

      - name: Run syntax check
        run: |
          flake8 .
